package com.example.hw9_1

import android.widget.ImageView

object Repository {
    var movieList = ArrayList<Movie>()

    init {
        movieList.add(Movie(R.drawable.ic_aladdin, "Aladdin"))
        movieList.add(Movie(R.drawable.rrr, "Aladdin"))
        movieList.add(Movie(R.drawable.ic_aladdin, "Aladdin"))
        movieList.add(Movie(R.drawable.rrr, "Aladdin"))
        movieList.add(Movie(R.drawable.ic_aladdin, "Aladdin"))
        movieList.add(Movie(R.drawable.rrr, "Aladdin"))
        movieList.add(Movie(R.drawable.ic_aladdin, "Aladdin"))
        movieList.add(Movie(R.drawable.rrr, "Aladdin"))
        movieList.add(Movie(R.drawable.ic_aladdin, "Aladdin"))
        movieList.add(Movie(R.drawable.rrr, "Aladdin"))
        movieList.add(Movie(R.drawable.ic_aladdin, "Aladdin"))
        movieList.add(Movie(R.drawable.rrr, "Aladdin"))
        movieList.add(Movie(R.drawable.ic_aladdin, "Aladdin"))
        movieList.add(Movie(R.drawable.rrr, "Aladdin"))
        movieList.add(Movie(R.drawable.ic_aladdin, "Aladdin"))
        movieList.add(Movie(R.drawable.rrr, "Aladdin"))
        movieList.add(Movie(R.drawable.ic_aladdin, "Aladdin"))
        movieList.add(Movie(R.drawable.rrr, "Aladdin"))
        movieList.add(Movie(R.drawable.ic_aladdin, "Aladdin"))
        movieList.add(Movie(R.drawable.rrr, "Aladdin"))
        movieList.add(Movie(R.drawable.ic_aladdin, "Aladdin"))
        movieList.add(Movie(R.drawable.rrr, "Aladdin"))
        movieList.add(Movie(R.drawable.ic_aladdin, "Aladdin"))
        movieList.add(Movie(R.drawable.rrr, "Aladdin"))
        movieList.add(Movie(R.drawable.ic_aladdin, "Aladdin"))
        movieList.add(Movie(R.drawable.rrr, "Aladdin"))
        movieList.add(Movie(R.drawable.ic_aladdin, "Aladdin"))
        movieList.add(Movie(R.drawable.rrr, "Aladdin"))
        movieList.add(Movie(R.drawable.ic_aladdin, "Aladdin"))
        movieList.add(Movie(R.drawable.rrr, "Aladdin"))
        movieList.add(Movie(R.drawable.ic_aladdin, "Aladdin"))
        movieList.add(Movie(R.drawable.rrr, "Aladdin"))
        movieList.add(Movie(R.drawable.ic_aladdin, "Aladdin"))
        movieList.add(Movie(R.drawable.rrr, "Aladdin"))
        movieList.add(Movie(R.drawable.ic_aladdin, "Aladdin"))
        movieList.add(Movie(R.drawable.rrr, "Aladdin"))
        movieList.add(Movie(R.drawable.ic_aladdin, "Aladdin"))
        movieList.add(Movie(R.drawable.rrr, "Aladdin"))
        movieList.add(Movie(R.drawable.ic_aladdin, "Aladdin"))
        movieList.add(Movie(R.drawable.rrr, "Aladdin"))
        movieList.add(Movie(R.drawable.ic_aladdin, "Aladdin"))
        movieList.add(Movie(R.drawable.rrr, "Aladdin"))
        movieList.add(Movie(R.drawable.ic_aladdin, "Aladdin"))
        movieList.add(Movie(R.drawable.rrr, "Aladdin"))
        movieList.add(Movie(R.drawable.ic_aladdin, "Aladdin"))
        movieList.add(Movie(R.drawable.rrr, "Aladdin"))
        movieList.add(Movie(R.drawable.ic_aladdin, "Aladdin"))
        movieList.add(Movie(R.drawable.rrr, "Aladdin"))
    }
}

data class Movie(var image: Int, var name: String)